// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using models;

namespace WebProjekat.Migrations
{
    [DbContext(typeof(ContextKlasa))]
    [Migration("20220321232422_V3")]
    partial class V3
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12");

            modelBuilder.Entity("models.Aerodrom", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Drzava")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Grad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID");

                    b.ToTable("Aerodromi");
                });

            modelBuilder.Entity("models.Klasa", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("Dodatak")
                        .HasColumnType("int");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID");

                    b.ToTable("Klase");
                });

            modelBuilder.Entity("models.Let", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("AerodromID")
                        .HasColumnType("int");

                    b.Property<int>("BrojMesta")
                        .HasColumnType("int");

                    b.Property<string>("DatumLeta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("KlasaID")
                        .HasColumnType("int");

                    b.Property<string>("VremeDolaska")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VremePolaska")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("AerodromID");

                    b.HasIndex("KlasaID");

                    b.ToTable("Letovi");
                });

            modelBuilder.Entity("models.Let", b =>
                {
                    b.HasOne("models.Aerodrom", "Aerodrom")
                        .WithMany()
                        .HasForeignKey("AerodromID");

                    b.HasOne("models.Klasa", "Klasa")
                        .WithMany()
                        .HasForeignKey("KlasaID");

                    b.Navigation("Aerodrom");

                    b.Navigation("Klasa");
                });
#pragma warning restore 612, 618
        }
    }
}
